<?php

namespace App\Models;

use App\Repositories\OutBoundRepository;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class SubAccount extends Model
{
    //修改框架默认的created_at/updated_at
    const UPDATED_AT = 'u_time';
    const CREATED_AT = 'c_time';

    public $table = 'c_sub_account';

    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    //用户被删除时，同时删除外呼号
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleted(function ($model) {
            $mod = new OutBoundRepository();
            $re = $mod->dropUser($model->id, true);
            Log::info('dropUser|' . $re);
        });

        static::creating(function ($model) {
            if ($model->password === null) {
                $model->password = 'hd' . $model->username;
            }
            $model->password = md5(md5($model->password) . 'partner');
        });

        static::updating(function ($model) {
            $info = $model->select(['password'])->where('id', '=', $model->id)->first()->toArray();
            if ($model->password != $info['password']) {
                $model->password = md5(md5($model->password) . 'partner');
            }
        });

        static::created(function ($model) {
            $calloutMod = new OutBoundRepository();
            $calloutMod->createUser($model->id, $model->username, $model->name, true);
        });

    }

    public function sub_account()
    {
        return $this->belongsTo(Company::class, 'id');
    }

    //修改框架自动维护的timestamp格式
    public function fromDateTime($value)
    {
        return strtotime(parent::fromDateTime($value));
    }
}
